#!/bin/sh
echo "remounting..."
adb remount
echo "changing permissions..."
adb shell chmod 777 /system/app
echo "pushing login apk..."
adb push GoogleLoginService-signed.apk /system/app/.
echo "pushing framework apk..."
adb push GoogleServicesFramework-signed.apk /system/app/.
echo "pushing phonesky (vending on <=4.1) apk..."
adb push Phonesky-signed.apk /system/app/.
echo "done"
